## Job to publish to npm on release
on:
  release:
    types: [created]
name: Publish to npm
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: build
        run: npm run build
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
